//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_xp_terminal {
            get {
                object obj = ResourceManager.GetObject("application_xp_terminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh_small {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_add {
            get {
                object obj = ResourceManager.GetObject("key_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squatting
        ///heliotrope
        ///migraine
        ///linotype.
        /// </summary>
        internal static string myWords {
            get {
                return ResourceManager.GetString("myWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_copy {
            get {
                object obj = ResourceManager.GetObject("page_white_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///to
        ///and
        ///a
        ///in
        ///is
        ///it
        ///you
        ///that
        ///he
        ///was
        ///for
        ///on
        ///are
        ///with
        ///as
        ///I
        ///his
        ///they
        ///be
        ///at
        ///one
        ///have
        ///this
        ///from
        ///or
        ///had
        ///by
        ///not
        ///word
        ///but
        ///what
        ///some
        ///we
        ///can
        ///out
        ///other
        ///were
        ///all
        ///there
        ///when
        ///up
        ///use
        ///your
        ///how
        ///said
        ///an
        ///each
        ///she
        ///which
        ///do
        ///their
        ///time
        ///if
        ///will
        ///way
        ///about
        ///many
        ///then
        ///them
        ///write
        ///would
        ///like
        ///so
        ///these
        ///her
        ///long
        ///make
        ///thing
        ///see
        ///him
        ///two
        ///has
        ///look
        ///more
        ///day
        ///could
        ///go
        ///come
        ///did
        ///number
        ///sound
        ///no
        ///most
        ///people
        ///my
        ///over
        ///know
        ///water
        ///than
        ///call
        ///first
        ///who
        ///may
        ///down
        ///side
        ///been
        ///now
        ///find
        ///any
        ///new
        ///work
        ///part
        ///take
        ///get
        ///place
        ///made
        ///live
        ///where
        ///after
        ///back
        ///little
        ///only [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abacus
        ///abdomen
        ///abdominal
        ///abide
        ///abiding
        ///ability
        ///ablaze
        ///able
        ///abnormal
        ///abrasion
        ///abrasive
        ///abreast
        ///abridge
        ///abroad
        ///abruptly
        ///absence
        ///absentee
        ///absently
        ///absinthe
        ///absolute
        ///absolve
        ///abstain
        ///abstract
        ///absurd
        ///accent
        ///acclaim
        ///acclimate
        ///accompany
        ///account
        ///accuracy
        ///accurate
        ///accustom
        ///acetone
        ///achiness
        ///aching
        ///acid
        ///acorn
        ///acquaint
        ///acquire
        ///acre
        ///acrobat
        ///acronym
        ///acting
        ///action
        ///activate
        ///activator
        ///active
        ///activism
        ///activist
        ///activity
        ///actress
        ///acts
        ///acutely
        ///acuteness
        ///aeration
        ///aerobics
        ///aer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words2 {
            get {
                return ResourceManager.GetString("words2", resourceCulture);
            }
        }
    }
}
